% Task 3
mover6 = importrobot('CPMOVER6.urdf');

% Task 3a:  Using the geometry contained within the file develop the forward kinematics for the robot, 
% given that it is defined in the URDF at its home position. Given the forward kinematics, calculate the 
% transformation matrix for the home position, do this using a point to point method
base_to_ee = getTransform(mover6, mover6.homeConfiguration, 'link1', 'base_link') * ...
                getTransform(mover6, mover6.homeConfiguration, 'link2', 'link1') * ...
                getTransform(mover6, mover6.homeConfiguration, 'link3', 'link2') * ...
                getTransform(mover6, mover6.homeConfiguration, 'link4', 'link3') * ...
                getTransform(mover6, mover6.homeConfiguration, 'link5', 'link4') * ...
                getTransform(mover6, mover6.homeConfiguration, 'link6', 'link5');

% Task 3b
tform = getTransform(mover6, mover6.homeConfiguration, 'link6', 'base_link');
